baseURL = 'https://thousandthstar.github.io/'
languageCode = 'en-us'
title = "ThousandthStar's blog"
theme = "PaperMod"
googleAnalytics = "G-ZP55MZZT7E"
disqusShortname = 'thousandthstar-github-io'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "I'm ThousandthStar, a hobbyist developper. I'm currently working on my game, 8bit Duels."

[[params.socialIcons]]
name = "github"
url = "https://github.com/ThousandthStar"

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@ThousandthStar"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/invite/NbBcF4bGU5"


